import {useDialog} from './ApexInteractions';
import {useState,useEffect} from 'react';
import {Icon} from './ApexUI';
export const localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const parse=d=>new Date(d+'T12:00:00');
const km=s=>parseFloat(s.dist)||0;
export function datedSessions(plan){return (plan?.sessions||[]).map((s,index)=>{let d=s.date;if(!d&&plan?.startDate){const base=parse(plan.startDate);base.setDate(base.getDate()+index);d=localDate(base);}return {...s,date:d,index};});}
export default function Training({plan,onChange,openCoach}){
 const [week,setWeek]=useState(()=>{const d=new Date();d.setDate(d.getDate()-(d.getDay()+6)%7);return localDate(d);}),[view,setView]=useState('week'),[edit,setEdit]=useState(null),[debrief,setDebrief]=useState(null),[feel,setFeel]=useState(3),[note,setNote]=useState(''),[notice,setNotice]=useState('');
 useDialog(!!debrief,()=>setDebrief(null));
 const sessions=datedSessions(plan).sort((a,b)=>(a.date||'').localeCompare(b.date||'')),days=Array.from({length:7},(_,i)=>{const d=parse(week);d.setDate(d.getDate()+i);return d;}),end=localDate(days[6]);
 const shown=view==='all'?sessions:sessions.filter(s=>s.date?s.date>=week&&s.date<=end:true),active=shown.filter(s=>s.type!=='Rest'),distance=active.filter(s=>s.type!=='Gym').reduce((n,s)=>n+km(s),0),done=active.filter(s=>s.done).length;
 const saveSessions=next=>onChange({...plan,sessions:next});
 const move=offset=>{const d=parse(week);d.setDate(d.getDate()+offset*7);setWeek(localDate(d));};
 const update=(i,data)=>{saveSessions(plan.sessions.map((s,j)=>j===i?{...s,...data}:s));};
 const complete=s=>{update(s.index,{done:!s.done});if(!s.done&&s.type!=='Rest'){setDebrief(s);setNote('');setFeel(3);}};
 const addSession=()=>setEdit({index:-1,date:localDate(new Date()),type:'Easy',dist:'',pace:'',shoe:'',notes:''});
 return <div className="training-page"><section className="training-banner"><div><span className="eyebrow">{plan?'YOUR TRAINING BLOCK':'MAKE THE NEXT STEP COUNT'}</span><h2>{plan?.title||'Something to build towards.'}</h2><p>{plan?'A plan is a direction. Make it work for your life.':'Build your first week with your coach, or add a session yourself.'}</p><button className="light-action" onClick={openCoach}><Icon name="coach" size={18}/> {plan?'Shape this with your coach':'Build with your coach'}</button></div><div className="training-orbits" aria-hidden="true"><i/><i/><i/><span>ONE DAY<br/>AT A TIME.</span></div></section>
 <div className="training-toolbar"><div className="week-control"><button onClick={()=>move(-1)} aria-label="Previous training week">‹</button><span>{days[0].toLocaleDateString('en-GB',{day:'numeric',month:'short'})} — {days[6].toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</span><button onClick={()=>move(1)} aria-label="Next training week">›</button></div><div className="apex-segments"><button aria-pressed={view==='week'} onClick={()=>setView('week')}>This week</button><button aria-pressed={view==='all'} onClick={()=>setView('all')}>All sessions</button></div><button className="primary-action" onClick={addSession}><Icon name="plus" size={18}/> Add session</button></div>
 <div className="training-summary"><div><span>Planned running</span><strong>{distance.toFixed(1)}<small> km</small></strong></div><div><span>Training sessions</span><strong>{active.length}<small> this view</small></strong></div><div><span>Completed</span><strong>{done}<small> / {active.length}</small></strong><div className="fuel-track"><i style={{width:`${active.length?done/active.length*100:0}%`}}/></div></div></div>
 {view==='week'&&<div className="training-week-strip">{days.map(d=>{const key=localDate(d),ds=sessions.filter(s=>s.date===key);return <button className={key===localDate(new Date())?'today':''} key={key} onClick={()=>setEdit(ds.length?ds[0]:{index:-1,date:key,type:'Easy',dist:'',pace:'',shoe:'',notes:''})}><span>{d.toLocaleDateString('en-GB',{weekday:'short'})}</span><strong>{d.getDate()}</strong><div>{ds.filter(s=>s.type!=='Rest').map((s,i)=><i key={i} className={s.done?'done':''}/>)}</div><small>{ds[0]?.type||'Open day'}</small></button>;})}</div>}
 {notice&&<p className="save-notice" role="status">{notice}</p>}
 <div className="session-list">{shown.length?shown.map(s=><article className={`training-session ${s.done?'session-complete':''} ${s.type==='Rest'?'rest-session':''}`} key={s.index}><div className="session-date"><span>{s.date?parse(s.date).toLocaleDateString('en-GB',{weekday:'short'}):s.day?.slice(0,3)||'Day'}</span><strong>{s.date?parse(s.date).getDate():String(s.index+1).padStart(2,'0')}</strong></div><div className="session-details"><div className="session-kind"><Icon name={s.type==='Gym'?'gym':s.type==='Rest'?'recovery':'activity'} size={18}/><span>{s.type}</span>{s.done&&<span className="completion-label">Completed</span>}</div><h3>{s.type==='Rest'?'A little room to recover.':s.type==='Gym'?'Build your foundation.':`${km(s)||'—'} km${s.pace&&s.pace!=='N/A'?' · '+s.pace.replace(/\/?km$/,'')+' /km':''}`}</h3><p>{s.notes||'Add the details that make this session yours.'}</p>{s.shoe&&s.shoe!=='N/A'&&<span className="session-shoe">{s.shoe}</span>}{s.debrief&&<p className="session-reflection">Reflection · {['Very hard','Hard','Steady','Good','Great'][s.debrief.feel-1]}{s.debrief.notes?' — '+s.debrief.notes:''}</p>}</div><div className="session-actions"><button onClick={()=>setEdit(s)}>Edit session</button>{s.type!=='Rest'&&<button className={s.done?'completed-button':'complete-button'} onClick={()=>complete(s)} aria-label={`${s.done?'Mark incomplete':'Complete'} ${s.type} ${s.date||s.day}`}>{s.done?'✓':'○'}</button>}</div></article>):<div className="training-empty"><Icon name="plan" size={36}/><h2>A little breathing room.</h2><p>No sessions scheduled for this view.</p><button className="secondary-action" onClick={addSession}>Plan a session <Icon name="plus" size={18}/></button></div>}</div>
 {edit&&<TrainingEditor value={edit} onClose={()=>setEdit(null)} onSave={s=>{const day=parse(s.date).toLocaleDateString('en-GB',{weekday:'long'}),{index,...clean}=s;if(index===-1)onChange({...plan,title:plan?.title||'My training plan',startDate:plan?.startDate||s.date,sessions:[...(plan?.sessions||[]),{...clean,day}]});else update(index,{...clean,day});setEdit(null);setNotice('Training plan updated.');}}/>}
 {debrief&&<div className="apex-modal-backdrop"><section className="apex-modal" role="dialog" aria-modal="true" aria-labelledby="reflection-title"><span className="eyebrow">THE SESSION IS ONLY HALF THE STORY</span><h2 id="reflection-title">How did it feel?</h2><p className="form-note">A quick reflection on your {debrief.type.toLowerCase()} session.</p><div className="feel-selector">{['Very hard','Hard','Steady','Good','Great'].map((l,i)=><button key={l} aria-pressed={feel===i+1} onClick={()=>setFeel(i+1)}><strong>{i+1}</strong>{l}</button>)}</div><textarea aria-label="Session reflection" rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Energy, legs, anything worth remembering…"/><div className="modal-actions"><button className="secondary-action" onClick={()=>setDebrief(null)}>Skip</button><button className="primary-action" onClick={()=>{update(debrief.index,{debrief:{feel,notes:note}});setDebrief(null);}}>Save reflection</button></div></section></div>}
 </div>;
}
function TrainingEditor({value,onClose,onSave}){
 useDialog(true,onClose);
 const [draft,setDraft]=useState(value),[error,setError]=useState('');
 useEffect(()=>{const el=document.getElementById('session-date');el?.focus();},[]);
 return <div className="apex-modal-backdrop"><form className="apex-modal" role="dialog" aria-modal="true" aria-labelledby="session-editor-title" onSubmit={e=>{e.preventDefault();if(!draft.date||!Number.isFinite(parse(draft.date).getTime())){setError('Choose a valid date.');return;}if(draft.type!=='Rest'&&draft.type!=='Gym'&&(!Number.isFinite(parseFloat(draft.dist))||parseFloat(draft.dist)<=0)){setError('Add a running distance greater than zero.');return;}onSave(draft);}}><div className="stage-top"><span className="eyebrow">MAKE IT YOURS</span><button type="button" className="close-button" onClick={onClose} aria-label="Close session editor">×</button></div><h2 id="session-editor-title">{value.index===-1?'One more step.':'A change of plan.'}</h2><div className="editor-grid"><label>Date<input id="session-date" type="date" required value={draft.date||''} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Session type<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}>{['Easy','Interval','Tempo','Long Run','Gym','Rest'].map(t=><option key={t}>{t}</option>)}</select></label>{!['Rest','Gym'].includes(draft.type)&&<><label>Distance (km)<input value={draft.dist||''} onChange={e=>setDraft({...draft,dist:e.target.value})} placeholder="8"/></label><label>Target pace<input value={draft.pace||''} onChange={e=>setDraft({...draft,pace:e.target.value})} placeholder="5:30–5:50"/></label></>}</div><label>Shoes<input value={draft.shoe||''} onChange={e=>setDraft({...draft,shoe:e.target.value})} placeholder="Optional"/></label><label>Session notes<textarea rows={3} value={draft.notes||''} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary-action" onClick={onClose}>Cancel</button><button className="primary-action" type="submit">Save session <Icon name="arrow" size={18}/></button></div></form></div>;
}
