// Compile-time-only isolated design fixture. Disabled in normal GitHub/Netlify builds.
export const PREVIEW=process.env.REACT_APP_APEX_PREVIEW==='true';
const day=(offset=0)=>{const d=new Date();d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
export const fixture={athlete:{id:0,firstname:'Caleb',lastname:'',city:'London'},stats:{all_run_totals:{distance:1250000,count:124,moving_time:375000},ytd_run_totals:{distance:620000,count:67,moving_time:185000},recent_run_totals:{distance:142000,count:16,moving_time:42000}},activities:Array.from({length:70},(_,i)=>({id:90000+i,name:i%7===5?'Walk':['Canal recovery','Legs and core','Heath long run','6 × 1 km at threshold'][i%4],type:i%7===5?'Walk':i%4===1?'WeightTraining':'Run',sport_type:i%7===5?'Walk':i%4===1?'WeightTraining':'Run',start_date:day(-i)+'T07:00:00Z',start_date_local:day(-i)+'T08:00:00Z',distance:i%4===1?0:[8200,0,18400,10400][i%4],moving_time:i%4===1?2900+i*40:Math.round([8200,0,18400,10400][i%4]/[2.9,0,2.95,3.35][i%4]),elapsed_time:i%4===1?3300:Math.round([8200,0,18400,10400][i%4]/[2.9,0,2.95,3.35][i%4])+140,average_speed:[2.9,0,2.95,3.35][i%4],max_speed:4.4,average_heartrate:143+i%8,max_heartrate:i%4===3?189:171,total_elevation_gain:52+i,average_cadence:87,workout_type:0,start_latlng:[51.5605,-0.1655],gear_id:i%4===1?null:['g1',null,'g1','g3'][i%4]})),whoop:{recoveries:{records:Array.from({length:7},(_,i)=>({created_at:day(-i)+'T06:00:00Z',score:{recovery_score:[71,64,58,82,61,78,84][i],hrv_rmssd_milli:78-i*2,resting_heart_rate:48+i%3}}))},sleeps:{records:Array.from({length:7},(_,i)=>({start:day(-i-1)+'T22:30:00Z',end:day(-i)+'T06:30:00Z',score:{sleep_performance_percentage:92,sleep_efficiency_percentage:95,respiratory_rate:14.5,stage_summary:{total_in_bed_time_milli:28800000,total_awake_time_milli:1200000,total_light_sleep_time_milli:14000000,total_slow_wave_sleep_time_milli:6200000,total_rem_sleep_time_milli:7400000},sleep_needed:{baseline_milli:28800000}}}))},cycles:{records:Array.from({length:7},(_,i)=>({start:day(-i)+'T06:00:00Z',score:{strain:12.4-i*.6,kilojoule:7500}}))}},plan:{title:'Marathon build · week 8',startDate:day(-((new Date().getDay()+6)%7)),sessions:Array.from({length:7},(_,i)=>({day:new Date(day(i)+'T12:00:00').toLocaleDateString('en-GB',{weekday:'long'}),date:day(i),type:['Easy','Gym','Interval','Easy','Rest','Tempo','Long Run'][i],dist:[8,0,10,7,0,12,24][i],pace:['5:40–6:00','N/A','4:20','5:40–6:00','N/A','4:50','5:45–6:05'][i],notes:['Relaxed effort. Keep the legs turning over.','Full-body strength and mobility.','Warm up, then controlled repeats.','Keep it comfortable.','Time to recharge.','Controlled and consistent.','Build time on your feet.'][i],done:false}))}};
fixture.gear=[{id:'g1',name:'Endorphin Speed 4',brand_name:'Saucony',distance:412000,primary:true},{id:'g2',name:'Adios Pro 4',brand_name:'Adidas',distance:188000},{id:'g3',name:'Pegasus 41',brand_name:'Nike',distance:671000}];
fixture.prefs={races:[{name:'Seville Marathon',date:'2027-02-21',distance:'42.195',target:'Sub 3:00',next:true}],currentPlan:fixture.plan,nutrition:{[day()]:{kcal:'2180',protein:'112',carbs:'242',fat:'68',meals:[{name:'Porridge, banana & almond butter',kcal:560,protein:24,carbs:78,fat:17,time:'08:00'},{name:'Chicken, rice & roasted vegetables',kcal:780,protein:52,carbs:96,fat:21,time:'13:15'},{name:'Yoghurt, granola & berries',kcal:840,protein:36,carbs:68,fat:30,time:'16:30'}]}},weightLog:[]};
const memory={prefs:fixture.prefs,plan:fixture.plan,chat:[]};
export const previewStore={loadUserPrefs:async()=>memory.prefs,saveUserPrefs:async p=>{memory.prefs=p;},loadTrainingPlan:async()=>memory.plan,saveTrainingPlan:async p=>{memory.plan=p;},loadChatHistory:async()=>memory.chat,saveChatHistory:async p=>{memory.chat=p;}};
export const previewFetch=async()=>({ok:false,json:async()=>({error:'This design preview does not call your live AI service.'})});

// Synthetic streams and detail for the design preview only, so the run detail can
// be checked without live Strava data. Never used in normal builds.
export function previewDetail(summary){
 const a={...summary};if(!a.distance)return {activity:{...a,calories:410,device_name:'COROS PACE 3'},streams:{}};
 const n=Math.round(a.moving_time/10),total=a.distance,time=[],distance=[],velocity_smooth=[],altitude=[],heartrate=[],cadence=[],latlng=[];
 let d=0;for(let i=0;i<n;i++){const k=i/n;const v=a.average_speed*(0.965+0.07*k)+Math.sin(i/7)*0.06;d+=v*10;time.push(i*10);distance.push(Math.min(total,d));velocity_smooth.push(v);
  altitude.push(62+28*Math.sin(k*Math.PI*3.2)+14*Math.sin(k*Math.PI*9+1));heartrate.push(Math.round(122+16*Math.min(1,k*4)+6*k+2*Math.sin(i/9)));cadence.push(86+Math.round(2*k+Math.sin(i/5)));
  const t=k*Math.PI*2;latlng.push([51.5605+0.0068*Math.sin(t)+0.0018*Math.sin(3*t),-0.1655+0.0105*Math.cos(t)+0.0022*Math.cos(2*t)]);}
 const scale=total/d;for(let i=0;i<n;i++)distance[i]=distance[i]*scale;
 return {activity:{...a,total_elevation_gain:212,elev_high:134,elev_low:58,max_heartrate:171,average_heartrate:141,average_cadence:87,calories:1312,suffer_score:96,pr_count:1,achievement_count:3,kudos_count:14,device_name:'COROS PACE 3',average_temp:12,gear:{name:'Saucony Endorphin Speed 4',distance:412000},
  best_efforts:[{name:'1k',moving_time:301},{name:'1 mile',moving_time:492,pr_rank:2},{name:'5k',moving_time:1661},{name:'10k',moving_time:3362,pr_rank:1}],
  laps:total<16000?undefined:[{distance:5000,moving_time:1745,average_speed:2.866,average_heartrate:139},{distance:5000,moving_time:1702,average_speed:2.938,average_heartrate:147},{distance:5000,moving_time:1683,average_speed:2.971,average_heartrate:150},{distance:total-15000,moving_time:a.moving_time-5130,average_speed:(total-15000)/(a.moving_time-5130),average_heartrate:156}]},
  streams:{time:{data:time},distance:{data:distance},velocity_smooth:{data:velocity_smooth},altitude:{data:altitude},heartrate:{data:heartrate},cadence:{data:cadence},latlng:{data:latlng}}};
}
// Preview only: ?morning shows Today before the run (drops today's activities).
if(PREVIEW&&typeof window!=='undefined'&&/[?&]morning/.test(window.location.search))fixture.activities=fixture.activities.filter(a=>!(a.start_date_local||a.start_date||'').startsWith(day()));
// Preview only: ?raceweek / ?raceday move the goal race close; ?sore logs a sore calf today.
if(PREVIEW&&typeof window!=='undefined'){const q=window.location.search,r=fixture.prefs.races?.[0];
 if(r&&/[?&]raceweek/.test(q))Object.assign(r,{date:day(4),time:'09:00',target:'2:59:30'});
 if(r&&/[?&]raceday/.test(q)){const t=new Date(Date.now()+75*60000);Object.assign(r,{date:day(),time:`${String(t.getHours()).padStart(2,'0')}:${String(t.getMinutes()).padStart(2,'0')}`,target:'2:59:30'});}
 if(/[?&]sore/.test(q))fixture.prefs.journal={...(fixture.prefs.journal||{}),[day()]:{energy:4,stress:2,soreness:3,body:{'calf-L':2},notes:''}};}
if(PREVIEW&&typeof window!=='undefined'&&/[?&]swiss/.test(window.location.search))fixture.prefs.settings={...(fixture.prefs.settings||{}),look:'swiss'};
// Preview only: the sample block started seven weeks ago, so the season lap reads week 8.
if(PREVIEW&&fixture.plan)fixture.plan.blockStart=day(-49);
// Preview only: ?chat seeds a two-day conversation to check the coach's date dividers.
if(PREVIEW&&typeof window!=='undefined'&&/[?&]chat/.test(window.location.search)){const at=(d,h,m)=>{const x=new Date();x.setDate(x.getDate()+d);x.setHours(h,m,0,0);return x.toISOString();};
 memory.chat=[{role:'assistant',content:'Ready when you are. Ask about today, your week, or what to change.'},{role:'user',at:at(-2,7,12),content:'Legs feel heavy today. Should I still do the tempo?'},{role:'assistant',at:at(-2,7,13),content:'Swap it for 6 km easy today and move the tempo to Friday. Heavy legs after a long run usually clear in 48 hours.'},{role:'user',at:at(0,6,58),content:'Feeling much better this morning.'},{role:'assistant',at:at(0,6,58),content:'Good, that fits your recovery jumping to 71. Friday’s tempo is on: 20 minutes at 4:45 /km.'}];}
