import {useState} from 'react';
import {useDialog} from './ApexInteractions';
import {localDate} from './ApexTraining';
import {RACES} from './data';
export function raceDate(r){return /^\d{4}-\d{2}-\d{2}$/.test(r.date||'')?r.date:null;}
export function focusRace(races=[]){const today=localDate(new Date());return races.filter(r=>!r.done&&!r.archived&&(!raceDate(r)||r.date>=today)).sort((a,b)=>Number(!!b.next)-Number(!!a.next)||(raceDate(a)||'9999').localeCompare(raceDate(b)||'9999'))[0];}
export default function Goals({userPrefs,onSavePrefs}){
 const races=userPrefs?.races||[],[draft,setDraft]=useState(null),[filter,setFilter]=useState('upcoming'),[undo,setUndo]=useState(null);
 const save=rows=>onSavePrefs({...userPrefs,races:rows});
 const focus=focusRace(races),today=localDate(new Date());
 const visible=races.map((r,index)=>({...r,index})).filter(r=>filter==='archive'?r.archived:filter==='completed'?r.done&&!r.archived:!r.done&&!r.archived).sort((a,b)=>(raceDate(a)||'9999').localeCompare(raceDate(b)||'9999'));
 return <section className="goals-app"><div className="section-label"><div><span className="eyebrow">YOUR GOALS, YOUR CALL</span><h2>Race calendar</h2></div><button className="primary-action" onClick={()=>setDraft({index:-1,name:'',date:'',target:'',distance:'42.195',next:false,done:false})}>Add race</button></div>
 {focus&&<div className="goal-focus"><div><span className="eyebrow">{focus.next?'PRIMARY GOAL':'ON YOUR HORIZON'}</span><h2>{focus.name}</h2><p>{focus.target||'Set your own ambition'} · {focus.distance?`${focus.distance} km`:'Distance not set'}</p></div><strong>{raceDate(focus)?Math.ceil((new Date(focus.date+'T12:00:00')-new Date(today+'T12:00:00'))/86400000):'—'}<small>days to go</small></strong></div>}
 <div className="apex-segments">{['upcoming','completed','archive'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f[0].toUpperCase()+f.slice(1)}</button>)}</div>
 <div className="race-gallery">{visible.map(r=><article className="race-pass" key={r.index}><div><span>{r.next?'PRIMARY GOAL':r.done?'COMPLETED':'RACE'}</span><button className="text-button" aria-label={`Edit ${r.name}`} onClick={()=>setDraft(r)}>Edit</button></div><h3>{r.name}</h3><p>{raceDate(r)?new Date(r.date+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'}):r.date||'Date to be decided'}</p><p>{r.distance?`${r.distance} km · `:''}{r.target||'No target set'}</p>{r.charity&&<small>{r.charity}</small>}<div className="goal-actions">{!r.done&&!r.archived&&<button onClick={()=>save(races.map((x,i)=>({...x,next:i===r.index})))}>{r.next?'Primary goal ✓':'Make primary'}</button>}<button onClick={()=>save(races.map((x,i)=>i===r.index?{...x,archived:!x.archived,next:false}:x))}>{r.archived?'Restore':'Archive'}</button><button onClick={()=>{setUndo({race:r,index:r.index});save(races.filter((_,i)=>i!==r.index));}}>Delete</button></div></article>)}</div>
 {!Array.isArray(userPrefs?.races)&&<div className="legacy-import"><p>The previous version used a built-in race list. Import it once to make those entries yours to edit, or start with a new race.</p><button className="secondary-action" onClick={()=>save(RACES.map(r=>({...r})))}>Import previous race list</button></div>}{!visible.length&&<div className="empty-goals"><h3>{filter==='upcoming'?'Your next finish line starts here.':'Nothing here yet.'}</h3><p>{filter==='upcoming'?'Add a race with your date, distance and target. You can change every detail later.':'Your race history stays yours to organise.'}</p></div>}
 {undo&&<div className="save-notice" role="status">Race deleted. <button className="text-button" onClick={()=>{const rows=[...races],{index,...r}=undo.race;rows.splice(Math.min(undo.index,rows.length),0,{...r,next:r.next&&!rows.some(x=>x.next)});save(rows);setUndo(null);}}>Undo</button></div>}
 {draft&&<GoalEditor race={draft} onClose={()=>setDraft(null)} onSave={r=>{const {index,...clean}=r;const rows=index<0?[...races,clean]:races.map((x,i)=>i===index?clean:x);save(rows.map((x,i)=>clean.next&&i!==(index<0?rows.length-1:index)?{...x,next:false}:x));setDraft(null);}}/>}</section>;
}
function GoalEditor({race,onClose,onSave}){useDialog(true,onClose);const [d,setD]=useState({...race,date:raceDate(race)||'',legacyDate:raceDate(race)?'':race.date}),set=(k,v)=>setD({...d,[k]:v});return <div className="apex-modal-backdrop"><form className="apex-modal" role="dialog" aria-modal="true" aria-labelledby="goal-title" onSubmit={e=>{e.preventDefault();const {legacyDate,...clean}=d;onSave({...clean,name:d.name.trim(),date:d.date||legacyDate||'',next:d.next&&!d.done&&!d.archived});}}><div className="stage-top"><h2 id="goal-title">{race.index<0?'Add a race':'Edit race'}</h2><button type="button" className="close-button" aria-label="Close race editor" onClick={onClose}>×</button></div><label>Race name<input required value={d.name} onChange={e=>set('name',e.target.value)}/></label><label>Race date<input type="date" value={d.date} onChange={e=>set('date',e.target.value)}/></label>{d.legacyDate&&<p className="form-note">Previous date: {d.legacyDate}. Kept until you choose an exact date.</p>}<label>Distance (km)<input type="number" min="0.1" step="0.001" value={d.distance||''} onChange={e=>set('distance',e.target.value)}/></label><label>Your target<input value={d.target||''} placeholder="e.g. Finish strong, or sub 3:20" onChange={e=>set('target',e.target.value)}/></label><label>Charity / reason<input value={d.charity||''} onChange={e=>set('charity',e.target.value)}/></label><label className="checkbox-label"><input type="checkbox" checked={!!d.next} onChange={e=>set('next',e.target.checked)}/>Primary goal</label><label className="checkbox-label"><input type="checkbox" checked={!!d.done} onChange={e=>set('done',e.target.checked)}/>Completed</label><div className="modal-actions"><button type="button" className="secondary-action" onClick={onClose}>Cancel</button><button className="primary-action" disabled={!d.name.trim()}>Save race</button></div></form></div>;}
