import {useState,useEffect} from 'react';
import {Icon} from './ApexUI';
import {LIFTS} from './data';
import {PREVIEW} from './ApexPreview';
import {localDate} from './ApexTraining';
export default function Strength({userPrefs,onSavePrefs,savedWorkout,openCoach}){
 const lifts=userPrefs?.lifts||LIFTS,history=userPrefs?.strengthHistory||[];
 const [tab,setTab]=useState('train'),[workout,setWorkout]=useState(()=>{if(PREVIEW)return null;try{const w=JSON.parse(localStorage.getItem('apex-strength-draft'));return w?.exercises?w:null;}catch{return null;}}),[editing,setEditing]=useState(false),[draft,setDraft]=useState(lifts),[notice,setNotice]=useState(''),[seconds,setSeconds]=useState(0);
 useEffect(()=>{if(!seconds)return;const id=setTimeout(()=>setSeconds(Math.max(0,seconds-1)),1000);return()=>clearTimeout(id);},[seconds]);
 useEffect(()=>{if(PREVIEW)return;try{if(workout)localStorage.setItem('apex-strength-draft',JSON.stringify(workout));else localStorage.removeItem('apex-strength-draft');}catch{}},[workout]);
 const start=(source=lifts,title='Strength session')=>{setWorkout({title,startedAt:new Date().toISOString(),exercises:source.map(e=>({name:e.name,reference:e.weight||'',sets:Array.from({length:Math.min(10,Number(e.sets)||3)},()=>({weight:'',reps:String(e.reps||10),done:false}))}))});setTab('train');};
 const update=(ei,si,patch)=>setWorkout({...workout,exercises:workout.exercises.map((e,i)=>i===ei?{...e,sets:e.sets.map((s,j)=>j===si?{...s,...patch}:s)}:e)});
 const completed=workout?.exercises.reduce((n,e)=>n+e.sets.filter(s=>s.done).length,0)||0,total=workout?.exercises.reduce((n,e)=>n+e.sets.length,0)||0;
 const volume=workout?.exercises.reduce((n,e)=>n+e.sets.filter(s=>s.done).reduce((a,s)=>a+Number(s.weight||0)*Number(s.reps||0),0),0)||0;
 const saveWorkout=()=>{const record={...workout,date:localDate(new Date()),endedAt:new Date().toISOString(),volume};onSavePrefs({...userPrefs,strengthHistory:[...history,record].slice(-100)});setWorkout(null);setSeconds(0);setNotice('Workout added to your strength history.');setTab('history');};
 return <div className="strength-page"><section className="strength-banner"><div><span className="eyebrow">STRONGER IS A PRACTICE</span><h2>Built one<br/>rep at a time.</h2><p>Give your running a stronger foundation.</p><button className="light-action" onClick={()=>openCoach?.()}><Icon name="coach" size={18}/> Build with your coach</button></div><div className="sculpted-weight" aria-hidden="true"><i/><i/><i/><i/><i/></div></section><div className="strength-toolbar"><div className="apex-segments">{[['train','Train'],['library','Your routine'],['history','History']].map(([id,l])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{l}</button>)}</div>{seconds>0&&<button className="rest-timer" onClick={()=>setSeconds(0)} aria-label="Stop rest timer">Rest · {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')} <span>×</span></button>}</div>{notice&&<p className="save-notice" role="status">{notice}</p>}
 {tab==='train'&&!workout&&<div className="routine-grid"><section className="routine-card"><span className="eyebrow">YOUR SAVED ROUTINE</span><h2>Show up.<br/>Build on it.</h2><div className="routine-count"><strong>{lifts.length}</strong><span>exercises in your rotation</span></div><div className="routine-preview">{lifts.slice(0,4).map((e,i)=><div key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{e.name}</p><span>{e.sets} × {e.reps}</span></div>)}</div><button className="primary-action" disabled={!lifts.length} onClick={()=>start()}>Start workout <Icon name="arrow" size={18}/></button></section><section className="strength-insight"><span className="eyebrow">THE LONGER VIEW</span><h2>Progress you<br/>can feel.</h2><div><strong>{history.length}</strong><span>workouts logged in APEX</span></div><p>Log the weight and reps for each set. Your completed work becomes a record to build on next time.</p>{savedWorkout?.exercises?.length>0&&<button className="secondary-action" onClick={()=>start(savedWorkout.exercises,savedWorkout.title||'Coach workout')}>Start coach’s workout <Icon name="arrow" size={17}/></button>}</section></div>}
 {tab==='train'&&workout&&<div className="live-workout"><div className="workout-progress"><div><span className="eyebrow">IN YOUR SESSION</span><h2>{workout.title}</h2></div><div><strong>{completed}<small> / {total}</small></strong><span>sets complete</span></div><div><strong>{volume.toLocaleString()}<small> kg</small></strong><span>recorded volume</span></div></div><div className="fuel-track"><i style={{width:`${total?completed/total*100:0}%`}}/></div>{workout.exercises.map((e,ei)=><section className="exercise-card" key={ei}><div className="exercise-heading"><span>{String(ei+1).padStart(2,'0')}</span><div><h3>{e.name}</h3><p>{e.reference?'Saved reference: '+e.reference:'Record the total load used, or zero for bodyweight.'}</p></div></div><div className="set-head"><span>SET</span><span>WEIGHT · KG</span><span>REPS</span><span>DONE</span></div>{e.sets.map((s,si)=><div className={`set-row ${s.done?'set-done':''}`} key={si}><span>{si+1}</span><input aria-label={`${e.name} set ${si+1} weight`} type="number" min="0" step="0.5" value={s.weight} onChange={ev=>update(ei,si,{weight:ev.target.value,done:false})} placeholder="0"/><input aria-label={`${e.name} set ${si+1} reps`} type="number" min="1" step="1" value={s.reps} onChange={ev=>update(ei,si,{reps:ev.target.value,done:false})}/><button aria-label={`${s.done?'Undo':'Complete'} ${e.name} set ${si+1}`} disabled={s.weight===''||!Number.isFinite(Number(s.weight))||Number(s.weight)<0||!Number.isInteger(Number(s.reps))||Number(s.reps)<=0} onClick={()=>{update(ei,si,{done:!s.done});if(!s.done)setSeconds(90);}}>{s.done?'✓':'○'}</button></div>)}<button className="text-button add-set" onClick={()=>setWorkout({...workout,exercises:workout.exercises.map((x,i)=>i===ei?{...x,sets:[...x.sets,{weight:'',reps:String(e.sets[e.sets.length-1]?.reps||10),done:false}]}:x)})}><Icon name="plus" size={16}/> Add a set</button></section>)}<div className="workout-finish"><p>{completed} completed sets will be included in your history.</p><button className="primary-action" disabled={!completed} onClick={saveWorkout}>Finish workout <Icon name="arrow" size={18}/></button></div></div>}
 {tab==='library'&&<section className="routine-library"><div className="section-label"><div><span className="eyebrow">A FOUNDATION TO RETURN TO</span><h2>Your exercise rotation.</h2></div><button className="secondary-action" onClick={()=>{setDraft(lifts);setEditing(!editing);}}>{editing?'Cancel':'Edit routine'}</button></div>{(editing?draft:lifts).map((e,i)=><div className="routine-edit-row" key={i}><span>{String(i+1).padStart(2,'0')}</span>{editing?<><label>Exercise<input value={e.name} onChange={ev=>setDraft(draft.map((x,j)=>j===i?{...x,name:ev.target.value}:x))}/></label><label>Sets<input type="number" min="1" max="10" value={e.sets} onChange={ev=>setDraft(draft.map((x,j)=>j===i?{...x,sets:ev.target.value}:x))}/></label><label>Reps<input type="number" min="1" value={e.reps} onChange={ev=>setDraft(draft.map((x,j)=>j===i?{...x,reps:ev.target.value}:x))}/></label><button aria-label={`Remove ${e.name||'exercise'}`} onClick={()=>setDraft(draft.filter((_,j)=>j!==i))}>×</button></>:<><h3>{e.name}</h3><p>{e.sets} sets × {e.reps} reps</p><span>{e.weight}</span></>}</div>)}{editing&&<div className="modal-actions"><button className="secondary-action" onClick={()=>setDraft([...draft,{name:'',sets:3,reps:10,weight:''}])}>Add exercise</button><button className="primary-action" disabled={!draft.length||draft.some(e=>!e.name.trim()||!Number.isInteger(Number(e.sets))||Number(e.sets)<1||Number(e.sets)>10||!Number.isInteger(Number(e.reps))||Number(e.reps)<1)} onClick={()=>{onSavePrefs({...userPrefs,lifts:draft});setEditing(false);setNotice('Routine updated.');}}>Save routine</button></div>}</section>}
 {tab==='history'&&<section className="routine-library"><span className="eyebrow">A RECORD OF SHOWING UP</span><h2>Your completed work.</h2>{history.length?[...history].reverse().map((w,i)=><details className="workout-history" key={i}><summary><div><span>{new Date(w.date+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'long'})}</span><h3>{w.title}</h3></div><strong>{(w.volume||0).toLocaleString()}<small> kg</small></strong></summary>{w.exercises.map((e,j)=><div key={j}><p>{e.name}</p><span>{e.sets.filter(s=>s.done).map(s=>`${s.weight}kg × ${s.reps}`).join(' · ')||'No completed sets'}</span></div>)}</details>):<p className="form-note">Finish your first workout to start your record.</p>}</section>}
 </div>;
}
