import {useDialog} from './ApexInteractions';
import {useState,useEffect} from 'react';
import {AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import {getActivity,getStreams} from './strava';
import {PREVIEW} from './ApexPreview';
import {Icon} from './ApexUI';
import {localDate} from './ApexTraining';
const run=a=>a.type==='Run'||a.sport_type==='Run';
const pace=s=>{if(!s)return '—';const v=Math.round(1000/s);return `${Math.floor(v/60)}:${String(v%60).padStart(2,'0')}`;};
const duration=s=>`${Math.floor((s||0)/3600)?Math.floor(s/3600)+'h ':''}${Math.floor((s||0)%3600/60)}m`;
export default function Activity({acts=[],gear=[],initialId=null}){
 const [type,setType]=useState('all'),[query,setQuery]=useState(''),[period,setPeriod]=useState('all'),[selected,setSelected]=useState(()=>acts.find(a=>a.id===initialId)||null);
 const start=new Date();start.setDate(start.getDate()-Number(period));
 const filtered=acts.filter(a=>(type==='all'||(type==='run'?run(a):!run(a)))&&(period==='all'||new Date(a.start_date_local||a.start_date)>=start)&&(!query||a.name?.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>new Date(b.start_date_local||b.start_date)-new Date(a.start_date_local||a.start_date));
 const total=filtered.reduce((s,a)=>s+(a.distance||0),0)/1000,time=filtered.reduce((s,a)=>s+(a.moving_time||0),0);
 const grid=Array.from({length:84},(_,i)=>{const d=new Date();d.setDate(d.getDate()-83+i);const key=localDate(d),items=acts.filter(a=>(a.start_date_local||a.start_date||'').slice(0,10)===key);return {key,mins:items.reduce((s,a)=>s+(a.moving_time||0)/60,0),count:items.length};});
 return <div className="activity-page"><section className="movement-studio"><div><span className="eyebrow">CONSISTENCY LEAVES A TRACE</span><h2>Small efforts.<br/>Lasting momentum.</h2><p>Your last 12 weeks of movement.</p><div className="movement-legend"><span>Less</span>{[0,1,2,3].map(i=><i key={i} className={'intensity-'+i}/>)}<span>More time</span></div></div><div className="movement-mosaic" aria-label="Activity minutes by day">{grid.map(d=><button key={d.key} className={`intensity-${d.mins===0?0:d.mins<40?1:d.mins<80?2:3}`} aria-label={`${d.key}: ${Math.round(d.mins)} minutes, ${d.count} activities`} title={`${d.key}: ${Math.round(d.mins)} min`} onClick={()=>{const a=acts.find(a=>(a.start_date_local||a.start_date||'').slice(0,10)===d.key);if(a)setSelected(a);}}/>)}</div></section>
 <div className="activity-controls"><div className="apex-segments">{[['all','Everything'],['run','Running'],['other','Other training']].map(([id,l])=><button key={id} aria-pressed={type===id} onClick={()=>setType(id)}>{l}</button>)}</div><div className="activity-search"><input aria-label="Search activities" placeholder="Find an activity…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Activity period" value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">All loaded</option><option value="30">Last 30 days</option><option value="7">Last 7 days</option></select></div></div>
 <div className="activity-totals"><div><span>Activities</span><strong>{filtered.length}</strong></div><div><span>Distance</span><strong>{total.toFixed(1)}<small> km</small></strong></div><div><span>Time moving</span><strong>{duration(time)}</strong></div></div>
 <div className="activity-gallery">{filtered.map((a,i)=><button className={`activity-story ${run(a)?'running-story':'strength-story'}`} key={a.id} onClick={()=>setSelected(a)}><div className="story-top"><span>{new Date(a.start_date_local||a.start_date).toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'})}</span><Icon name={run(a)?'activity':'gym'} size={20}/></div><div className="story-art" aria-hidden="true">{run(a)?<RouteLine encoded={a.map?.summary_polyline}/>:<div className="dumbbell-art"><i/><i/><i/></div>}</div><div className="story-content"><span>{run(a)?'RUNNING':(a.type||'ACTIVITY').replace(/([a-z])([A-Z])/g,'$1 $2').toUpperCase()}</span><h3>{a.name}</h3><div className="story-stats"><div><strong>{a.distance?(a.distance/1000).toFixed(1):Math.round((a.moving_time||0)/60)}</strong><span>{a.distance?'km':'min'}</span></div><div><strong>{run(a)?pace(a.average_speed):duration(a.moving_time)}</strong><span>{run(a)?'/km':'duration'}</span></div><span className="story-arrow"><Icon name="arrow" size={18}/></span></div></div></button>)}</div>{filtered.length===0&&<div className="training-empty"><h2>No matching movement.</h2><p>Try another search or time range.</p></div>}
 {gear.length>0&&<section className="gear-shelf"><div className="section-label"><div><span className="eyebrow">THE KIT THAT CARRIES YOU</span><h2>In your rotation.</h2></div></div><div>{gear.map(g=><div key={g.id}><Icon name="activity"/><h3>{g.name||g.nickname}</h3><strong>{Math.round((g.distance||0)/1000)}<small> km</small></strong></div>)}</div></section>}
 <p className="form-note">Based on the activities loaded from your existing Strava connection. This may be a subset of your full history.</p>
 {selected&&<ActivityDetail summary={selected} onClose={()=>setSelected(null)}/>}
 </div>;
}
function decode(encoded){if(!encoded)return [];let index=0,lat=0,lng=0,out=[];try{while(index<encoded.length){let shift=0,result=0,b;do{b=encoded.charCodeAt(index++)-63;result|=(b&31)<<shift;shift+=5;}while(b>=32&&index<encoded.length);lat+=result&1?~(result>>1):result>>1;shift=0;result=0;do{b=encoded.charCodeAt(index++)-63;result|=(b&31)<<shift;shift+=5;}while(b>=32&&index<encoded.length);lng+=result&1?~(result>>1):result>>1;out.push([lng/1e5,lat/1e5]);}}catch{return [];}return out;}
function RouteLine({encoded}){const pts=decode(encoded);if(pts.length<2)return <div className="abstract-contours"><svg viewBox="0 0 400 140" preserveAspectRatio="none">{Array.from({length:8},(_,i)=><path key={i} d={`M-15 ${105+i*6}C70 ${120+i*4},75 ${10+i*9},175 ${55+i*7}S290 ${135+i*3},420 ${20+i*12}`} fill="none" stroke="currentColor" strokeOpacity={.45-i*.025}/>)}</svg></div>;const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),minX=Math.min(...xs),minY=Math.min(...ys),dx=Math.max(...xs)-minX,dy=Math.max(...ys)-minY,scale=110/Math.max(dx,dy,.0001);const path=pts.map(([x,y],i)=>`${i?'L':'M'}${200+(x-minX-dx/2)*scale},${75-(y-minY-dy/2)*scale}`).join(' ');return <svg viewBox="0 0 400 150" role="img" aria-label="Activity route outline"><path d={path} fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg>;}
function ActivityDetail({summary,onClose}){
 useDialog(true,onClose);
 const [activity,setActivity]=useState(summary),[streams,setStreams]=useState({}),[loading,setLoading]=useState(!PREVIEW),[error,setError]=useState(''),[metric,setMetric]=useState('heartrate');
 useEffect(()=>{let active=true;if(PREVIEW)return;Promise.all([getActivity(summary.id),getStreams(summary.id)]).then(([a,s])=>{if(active){setActivity(a);setStreams(s||{});}}).catch(()=>{if(active)setError('Detailed streams could not be loaded. Your activity summary is shown.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[summary.id]);
 const source=streams[metric]?.data||[],dist=streams.distance?.data||[],chart=source.map((v,i)=>({distance:dist[i]!=null?+(dist[i]/1000).toFixed(2):i,value:v})).filter((_,i)=>i%Math.max(1,Math.floor(source.length/350))===0);
 return <div className="apex-modal-backdrop activity-detail-backdrop"><section className="activity-detail" role="dialog" aria-modal="true" aria-labelledby="activity-detail-title"><div className="detail-cover"><button className="detail-close" onClick={onClose}>Close ×</button><span className="eyebrow">{new Date(activity.start_date_local||activity.start_date).toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'})}</span><h2 id="activity-detail-title">{activity.name}</h2><RouteLine encoded={activity.map?.polyline||activity.map?.summary_polyline}/><div className="detail-headline"><strong>{((activity.distance||0)/1000).toFixed(2)}<small> km</small></strong><span>{duration(activity.moving_time)} moving time</span></div></div><div className="detail-body"><div className="detail-metrics">{[['Average pace',pace(activity.average_speed),'/km'],['Average heart rate',activity.average_heartrate?Math.round(activity.average_heartrate):'—','bpm'],['Elevation gain',activity.total_elevation_gain??'—','m'],['Cadence',activity.average_cadence?Math.round(activity.average_cadence*(run(activity)?2:1)):'—',run(activity)?'spm':'rpm']].map(([l,v,u])=><div key={l}><span>{l}</span><strong>{v}<small> {u}</small></strong></div>)}</div>{error&&<p className="form-error">{error}</p>}<div className="section-label"><h2>Inside the effort.</h2><div className="apex-segments">{[['heartrate','Heart rate'],['altitude','Elevation']].map(([id,l])=><button key={id} aria-pressed={metric===id} onClick={()=>setMetric(id)}>{l}</button>)}</div></div><div className="effort-chart">{chart.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><XAxis dataKey="distance" minTickGap={40} tick={{fontSize:10,fill:'#8b8196'}} axisLine={false} tickLine={false}/><YAxis domain={['auto','auto']} tick={{fontSize:10,fill:'#8b8196'}} axisLine={false} tickLine={false} width={35}/><Tooltip formatter={v=>[Math.round(v),metric==='heartrate'?'bpm':'m']}/><Area dataKey="value" type="monotone" stroke="#a287b6" fill="#e9e1ef" strokeWidth={2} isAnimationActive={false}/></AreaChart></ResponsiveContainer>:<p className="form-note">{loading?'Loading your activity streams…':PREVIEW?'Detailed streams appear with your real activities.':'No detailed stream is available for this activity.'}</p>}</div>{activity.laps?.length>0&&<div className="split-list"><h2>Lap by lap.</h2>{activity.laps.map((l,i)=><div key={i}><span>{String(i+1).padStart(2,'0')}</span><strong>{(l.distance/1000).toFixed(2)} km</strong><span>{pace(l.average_speed)} /km</span><span>{l.average_heartrate?Math.round(l.average_heartrate)+' bpm':'—'}</span></div>)}</div>}{activity.best_efforts?.length>0&&<div className="split-list"><h2>Best efforts.</h2>{activity.best_efforts.map((e,i)=><div key={i}><strong>{e.name}</strong><span>{duration(e.moving_time||e.elapsed_time)}</span></div>)}</div>}</div></section></div>;
}
