import {useState,useRef} from 'react';
import {Icon} from './ApexUI';
import {PREVIEW} from './ApexPreview';
const fields=[['kcal','Energy','kcal'],['protein','Protein','g'],['carbs','Carbs','g'],['fat','Fat','g']];
const defaults={kcal:3000,protein:140,carbs:300,fat:80};
const blank={name:'',kcal:'',protein:'',carbs:'',fat:''};
export default function Nutrition({userPrefs,onSavePrefs}){
 const now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
 const [undoMeal,setUndoMeal]=useState(null);
 const [selectedDate,setSelectedDate]=useState(today),[editIndex,setEditIndex]=useState(null);
 const log=userPrefs?.nutrition||{},entry=log[selectedDate]||{kcal:'0',protein:'0',carbs:'0',fat:'0',meals:[]};
 const targets={...defaults,...userPrefs?.nutritionTargets};
 const [tab,setTab]=useState('today'),[mode,setMode]=useState('describe'),[text,setText]=useState(''),[photo,setPhoto]=useState(null),[draft,setDraft]=useState(blank),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[weight,setWeight]=useState('');
 const [targetDraft,setTargetDraft]=useState(targets),file=useRef(null);
 const saveEntry=e=>onSavePrefs({...userPrefs,nutrition:{...log,[selectedDate]:e}});
 const analyse=async()=>{setError('');if(PREVIEW){setError('AI is connected only in your live app. You can try manual meal logging in this preview.');return;}setBusy(true);try{
  const content=[];if(photo)content.push({type:'image',source:{type:'base64',media_type:photo.type,data:photo.data}});
  content.push({type:'text',text:`Estimate this meal${text?': '+text:''}. Return only JSON: {"name":"meal name","kcal":number,"protein":number,"carbs":number,"fat":number}. Use UK portions.`});
  const res=await fetch('/.netlify/functions/claude-chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({system:'Estimate nutrition. Return only the requested JSON.',messages:[{role:'user',content}]})});
  const data=await res.json();if(!res.ok||data.error)throw new Error('The food estimate could not be completed. Try again or add the meal manually.');
  const parsed=JSON.parse((data.content?.[0]?.text||'').replace(/```json|```/g,'').trim());
  if(!parsed.name||fields.some(([k])=>!Number.isFinite(parsed[k])||parsed[k]<0))throw new Error('The estimate was incomplete. Please add the meal manually.');
  setDraft(parsed);setReview(true);
 }catch(e){setError(e.message||'Unable to estimate this meal.');}finally{setBusy(false);}};
 const add=()=>{if(!draft.name.trim()||fields.some(([k])=>draft[k]===''||!Number.isFinite(Number(draft[k]))||Number(draft[k])<0)){setError('Add a meal name and a valid value for each nutrient.');return;}
  const meal={name:draft.name.trim(),time:editIndex!==null?entry.meals[editIndex].time:new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}),...Object.fromEntries(fields.map(([k])=>[k,Number(draft[k])]))};
  const old=editIndex!==null?entry.meals[editIndex]:null;const e={...entry,meals:old?entry.meals.map((m,i)=>i===editIndex?meal:m):[...(entry.meals||[]),meal]};fields.forEach(([k])=>e[k]=String(Math.max(0,Math.round((Number(entry[k])||0)-(Number(old?.[k])||0)+meal[k]))));setEditIndex(null);saveEntry(e);setDraft(blank);setReview(false);setText('');setPhoto(null);setError('');setNotice(editIndex!==null?'Meal updated.':'Meal added to your log.');};
 const remove=i=>{setUndoMeal({meal:entry.meals[i],date:selectedDate});const m=entry.meals[i],e={...entry,meals:entry.meals.filter((_,j)=>j!==i)};fields.forEach(([k])=>e[k]=String(Math.max(0,(Number(entry[k])||0)-(Number(m[k])||0))));saveEntry(e);setNotice('Meal removed.');};
 const upload=e=>{const f=e.target.files?.[0];if(!f)return;if(!['image/jpeg','image/png','image/webp','image/gif'].includes(f.type)||f.size>4*1024*1024){setError('Choose a JPG, PNG, WebP or GIF smaller than 4 MB.');return;}const r=new FileReader();r.onload=()=>{setPhoto({url:r.result,data:r.result.split(',')[1],type:f.type});setError('');};r.readAsDataURL(f);};
 return <div className="nutrition-app"><div className="apex-segments" role="tablist" aria-label="Nutrition views">{[['today','Today'],['history','History'],['targets','Your targets']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {notice&&<p className="save-notice" role="status">{notice}</p>}{undoMeal&&<button className="text-button" onClick={()=>{const source=log[undoMeal.date]||{},e={...source,meals:[...(source.meals||[]),undoMeal.meal]};fields.forEach(([k])=>e[k]=String((Number(source[k])||0)+(Number(undoMeal.meal[k])||0)));onSavePrefs({...userPrefs,nutrition:{...log,[undoMeal.date]:e}});setUndoMeal(null);setNotice('Meal restored.');}}>Undo meal deletion</button>}
 {tab==='today'&&<><label className="food-date">Food diary date<input type="date" required max={today} value={selectedDate} onChange={e=>{if(e.target.value){setSelectedDate(e.target.value);setEditIndex(null);setDraft(blank);setReview(false);}}}/></label><div className="nutrition-overview"><div className="energy-summary"><span className="eyebrow">{selectedDate===today?'TODAY’S INTAKE':'DAILY INTAKE'}</span><strong>{Number(entry.kcal||0).toLocaleString()}<small>kcal</small></strong><p>{Math.max(0,targets.kcal-Number(entry.kcal||0)).toLocaleString()} kcal to your target</p><div className="energy-orbit" aria-hidden="true" style={{'--progress':`${Math.min(100,Number(entry.kcal||0)/targets.kcal*100)}%`}}/></div><div className="macro-summary">{fields.slice(1).map(([k,label,u])=><div key={k} className={'macro-row macro-'+k}><div><span>{label}</span><strong>{entry[k]||0}<small> / {targets[k]} {u}</small></strong></div><div className="fuel-track"><i style={{width:`${Math.min(100,Number(entry[k]||0)/targets[k]*100)}%`}}/></div></div>)}</div></div>
 <div className="nutrition-columns"><section className="food-composer"><span className="eyebrow">MAKE ROOM FOR GOOD FOOD</span><h2>What’s on your plate?</h2><div className="composer-tabs">{[['describe','Describe or photograph'],['manual','Add manually']].map(([id,label])=><button key={id} className={mode===id?'active':''} onClick={()=>{setMode(id);setError('');}}>{label}</button>)}</div>
 {mode==='describe'&&!review&&<><textarea aria-label="Describe your meal" placeholder="Chicken, rice and roasted vegetables. A generous bowl…" value={text} onChange={e=>setText(e.target.value)} rows={4}/>{photo&&<div className="food-photo"><img src={photo.url} alt="Meal to estimate"/><button onClick={()=>setPhoto(null)}>Remove photo</button></div>}<div className="composer-actions"><input ref={file} type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={upload} hidden/><button className="secondary-action" onClick={()=>file.current.click()}><Icon name="plus" size={17}/> Add photo</button><button className="primary-action" disabled={busy||(!text.trim()&&!photo)} onClick={analyse}>{busy?'Estimating…':'Estimate meal'}<Icon name="arrow" size={17}/></button></div><p className="form-note">AI estimates are approximate. Review before adding.</p></>}
 {(mode==='manual'||review)&&<div className="meal-fields">{review&&<p className="form-note">Review and adjust your estimate.</p>}<label>Meal name<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="e.g. Breakfast bowl"/></label><div>{fields.map(([k,label,u])=><label key={k}>{label} ({u})<input type="number" min="0" step="any" value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}</div><button className="primary-action" onClick={add}>{editIndex!==null?'Save meal':selectedDate===today?'Add to today':'Add to day'} <Icon name="plus" size={17}/></button>{editIndex!==null&&<button className="secondary-action" onClick={()=>{setEditIndex(null);setDraft(blank);}}>Cancel edit</button>}{review&&<button className="secondary-action" onClick={()=>setReview(false)}>Cancel estimate</button>}</div>}{error&&<p className="form-error" role="alert">{error}</p>}</section>
 <section className="food-diary"><div className="stage-top"><span className="eyebrow">YOUR FOOD DIARY</span><span>{entry.meals?.length||0} meals</span></div><h2>A day, well fuelled.</h2>{entry.meals?.length?entry.meals.map((m,i)=><div className="diary-meal" key={i}><div className="meal-number">{String(i+1).padStart(2,'0')}</div><div><span>{m.time}</span><h3>{m.name}</h3><p>{m.kcal} kcal <span>·</span> {m.protein}g protein</p></div><div className="meal-tools"><button aria-label={`Edit ${m.name}`} onClick={()=>{setDraft(m);setEditIndex(i);setMode('manual');setReview(false);}}>Edit</button><button aria-label={`Repeat ${m.name}`} onClick={()=>{setDraft({...m});setEditIndex(null);setMode('manual');setReview(false);}}>Repeat</button><button aria-label={`Remove ${m.name}`} onClick={()=>remove(i)}>×</button></div></div>):<p className="form-note">Start with your first meal. Every entry helps complete the picture.</p>}</section></div>
 <section className="weight-strip"><div><span className="eyebrow">BODY WEIGHT</span><h2>Track the longer view.</h2></div><div><label htmlFor="weight-entry">Today’s weight (kg)</label><div className="weight-input"><input id="weight-entry" type="number" min="1" step="0.1" value={weight} onChange={e=>setWeight(e.target.value)} placeholder="e.g. 60.5"/><button className="primary-action" disabled={!Number(weight)||Number(weight)<=0} onClick={()=>{onSavePrefs({...userPrefs,weightLog:[...(userPrefs?.weightLog||[]).filter(w=>w.date!==today),{date:today,weight:Number(weight)}].slice(-60)});setWeight('');setNotice('Weight added to your log.');}}>Save</button></div></div></section></>}
 {tab==='history'&&<><WeightTrend entries={userPrefs?.weightLog||[]}/><section className="food-diary history-panel"><h2>Your recent nutrition.</h2>{Object.entries(log).sort(([a],[b])=>b.localeCompare(a)).slice(0,30).map(([date,e])=><div className="history-row" key={date}><div><h3>{new Date(date+'T12:00:00').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'short'})}</h3><p>{e.meals?.map(m=>m.name).join(' · ')||'Daily totals'}</p></div><strong>{Number(e.kcal||0).toLocaleString()}<small> kcal</small></strong><button className="text-button" onClick={()=>{setSelectedDate(date);setTab('today');setEditIndex(null);setDraft(blank);}}>Open day</button></div>)}{Object.keys(log).length===0&&<p>No meals logged yet.</p>}</section></>}
 {tab==='targets'&&<section className="food-composer target-panel"><span className="eyebrow">PERSONAL TARGETS</span><h2>A little direction for every day.</h2><p className="form-note">Set the daily targets you’re working towards.</p><div className="meal-fields"><div>{fields.map(([k,label,u])=><label key={k}>{label} ({u})<input type="number" min="1" value={targetDraft[k]} onChange={e=>setTargetDraft({...targetDraft,[k]:e.target.value})}/></label>)}</div><button className="primary-action" disabled={fields.some(([k])=>!Number.isFinite(Number(targetDraft[k]))||Number(targetDraft[k])<=0)} onClick={()=>{onSavePrefs({...userPrefs,nutritionTargets:Object.fromEntries(fields.map(([k])=>[k,Number(targetDraft[k])]))});setNotice('Daily targets updated.');}}>Save targets</button></div></section>}
 </div>;
}

function WeightTrend({entries}){const points=entries.filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x.date)&&Number(x.weight)>0).sort((a,b)=>a.date.localeCompare(b.date)).slice(-14),values=points.map(p=>Number(p.weight));if(!points.length)return <section className="weight-history"><h2>Your weight over time</h2><p>Log your weight to start a record of your progress.</p></section>;const min=Math.min(...values)-.5,max=Math.max(...values)+.5,first=new Date(points[0].date+'T12:00:00').getTime(),last=new Date(points[points.length-1].date+'T12:00:00').getTime(),path=points.map((p,i)=>`${i?'L':'M'}${20+(new Date(p.date+'T12:00:00').getTime()-first)/(last-first||1)*460},${110-(Number(p.weight)-min)/(max-min)*90}`).join(' ');return <section className="weight-history"><span className="eyebrow">YOUR RECORDED WEIGHT</span><h2>{values[values.length-1]} <small>kg</small></h2>{points.length>1&&<svg viewBox="0 0 500 130" role="img" aria-label={`Weight from ${values[0]} to ${values[values.length-1]} kilograms between ${points[0].date} and ${points[points.length-1].date}`}><path d={path} fill="none" stroke="#89719f" strokeWidth="3"/></svg>}<p>{points[0].date} → {points[points.length-1].date} · {points.length} readings. Individual measurements fluctuate.</p><details><summary>View measurements</summary>{points.map((p,i)=><p key={i}>{p.date} · {p.weight} kg</p>)}</details></section>;}
