import {useState} from 'react';
import {AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer,ReferenceLine} from 'recharts';
import {Icon} from './ApexUI';
import RecoverySculpture from './RecoverySculpture';
const round=(v,d=0)=>v==null?'—':Number(v).toFixed(d);
const time=v=>v?new Date(v).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}):'—';
const duration=v=>v==null?'—':`${Math.floor(v/3600000)}h ${Math.round(v%3600000/60000)}m`;
export default function Recovery({whoop,whoopOk,connectWhoop}){
 const [metric,setMetric]=useState('recovery'),[range,setRange]=useState(7),[selected,setSelected]=useState(0);
 const recs=[...(whoop?.recoveries?.records||[])].sort((a,b)=>new Date(b.created_at||b.updated_at)-new Date(a.created_at||a.updated_at));
 const record=recs[selected],score=record?.score?.recovery_score??null;
 const recordDay=(record?.created_at||record?.updated_at||'').slice(0,10);
 const sleep=(whoop?.sleeps?.records||[]).find(s=>record?.sleep_id&&s.id===record.sleep_id)||(whoop?.sleeps?.records||[]).find(s=>(s.end||'').slice(0,10)===recordDay);
 const stage=sleep?.score?.stage_summary,cycle=(whoop?.cycles?.records||[]).find(c=>c.id&&c.id===record?.cycle_id)||(whoop?.cycles?.records||[]).find(c=>(c.start||'').slice(0,10)===recordDay);
 const configs={recovery:{label:'Recovery',unit:'%',key:'recovery_score',color:'#8c76c1'},hrv:{label:'Heart rate variability',unit:'ms',key:'hrv_rmssd_milli',color:'#8c76c1'},rhr:{label:'Resting heart rate',unit:'bpm',key:'resting_heart_rate',color:'#bb8f76'}};
 const config=configs[metric],history=recs.slice(0,range).reverse().map(r=>({date:new Date(r.created_at||r.updated_at).toLocaleDateString('en-GB',{day:'numeric',month:'short'}),value:r.score?.[config.key]??null}));
 const values=history.map(r=>r.value).filter(v=>v!=null),average=values.length?values.reduce((a,b)=>a+b,0)/values.length:null;
 const previous=recs.slice(selected+1,selected+8).map(r=>r.score?.hrv_rmssd_milli).filter(v=>v!=null),baseline=previous.length?previous.reduce((a,b)=>a+b,0)/previous.length:null;
 const delta=baseline&&record?.score?.hrv_rmssd_milli!=null?Math.round((record.score.hrv_rmssd_milli/baseline-1)*100):null;
 const stages=[['Deep',stage?.total_slow_wave_sleep_time_milli,'#665185'],['REM',stage?.total_rem_sleep_time_milli,'#a58ebf'],['Light',stage?.total_light_sleep_time_milli,'#d1c3dd'],['Awake',stage?.total_awake_time_milli,'#e9e0ef']];
 const total=stages.reduce((s,[,v])=>s+(v||0),0);
 const actual=stage?total-(stage.total_awake_time_milli||0):null;
 if(!whoopOk)return <section className="recovery-connect"><div><span className="eyebrow">RECOVERY STARTS WITH A BASELINE</span><h2>Listen a little closer.</h2><p>Connect WHOOP to bring your sleep, recovery and daily strain into the same picture.</p><button className="primary-action" onClick={connectWhoop}>Connect WHOOP <Icon name="arrow"/></button></div><RecoverySculpture score={null}/></section>;
 return <div className="recovery-page"><div className="recovery-day-picker"><div><span className="eyebrow">A MOMENT TO CHECK IN</span><p>{record?new Date(record.created_at||record.updated_at).toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'}):'Waiting for recovery data'}</p></div><label>View day<select aria-label="Recovery day" value={selected} onChange={e=>setSelected(Number(e.target.value))}>{recs.slice(0,14).map((r,i)=><option key={i} value={i}>{i===0?'Latest · ':''}{new Date(r.created_at||r.updated_at).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</option>)}</select></label></div>
 <div className="recovery-explorer"><section className="recovery-object"><div className="stage-top"><span className="eyebrow">WHOOP RECOVERY</span><Icon name="recovery"/></div><div className="sculpture-wrap"><RecoverySculpture score={score}/><div className="sculpture-score"><strong>{score==null?'—':Math.round(score)}{score!=null&&<sup>%</sup>}</strong><span>{score==null?'Awaiting data':score>=67?'Well recovered':score>=34?'Moderate recovery':'Low recovery'}</span></div></div><h2>{score==null?'Your signals belong here.':score>=67?'A strong foundation.':score>=34?'Take the day as it comes.':'Recovery is work, too.'}</h2><p>{score==null?'Your next synced recovery will appear here.':'A snapshot of your body’s recovery. Pair it with how you feel.'}</p></section>
 <div className="signal-grid">{[['HRV',round(record?.score?.hrv_rmssd_milli),'ms',delta==null?'Your nervous system’s daily signal':`${delta>=0?'+':''}${delta}% vs previous ${previous.length}-day average`,'hrv'],['Resting heart rate',round(record?.score?.resting_heart_rate),'bpm','Your heart rate at rest','rhr'],['Daily strain',round(cycle?.score?.strain,1),'/ 21','WHOOP’s measure of daily exertion',null],['Respiratory rate',round(sleep?.score?.respiratory_rate,1),'br/min','Measured during sleep',null]].map(([label,value,unit,note,id])=><button key={label} className={`signal-tile ${id===metric?'chosen':''}`} onClick={id?()=>setMetric(id):undefined} disabled={!id}><span>{label}</span><strong>{value}<small> {unit}</small></strong><p>{note}</p>{id&&<Icon name="arrow" size={16}/>}</button>)}</div></div>
 <section className="sleep-studio"><div className="sleep-title"><span className="eyebrow">THE NIGHT BEHIND YOUR DAY</span><h2>Time to restore.</h2><p>{time(sleep?.start)} <span>—</span> {time(sleep?.end)}</p></div><div className="sleep-duration"><strong>{duration(actual)}</strong><span>Time asleep</span></div><div className="sleep-performance"><strong>{round(sleep?.score?.sleep_performance_percentage)}<small>%</small></strong><span>Sleep performance</span></div><div className="sleep-composition"><div className="sleep-stage-bar" aria-label="Total time in each sleep stage">{stages.map(([label,value,color])=><div key={label} title={`${label}: ${duration(value)}`} style={{width:`${total?(value||0)/total*100:25}%`,background:color}}/>)}</div><div className="stage-legend">{stages.map(([label,value,color])=><div key={label}><span><i style={{background:color}}/>{label}</span><strong>{duration(value)}</strong></div>)}</div><p className="form-note">Stage totals for this sleep, not a minute-by-minute timeline.</p></div></section>
 <section className="trend-studio"><div className="section-label"><div><span className="eyebrow">A LITTLE DISTANCE. A CLEARER PATTERN.</span><h2>Your recovery over time.</h2></div><div className="range-control">{[7,14,30].map(n=><button key={n} className={range===n?'active':''} onClick={()=>setRange(n)}>{n} days</button>)}</div></div><div className="trend-top"><div className="apex-segments" role="tablist" aria-label="Recovery metric">{Object.entries(configs).map(([id,c])=><button key={id} role="tab" aria-selected={metric===id} onClick={()=>setMetric(id)}>{id==='hrv'?'HRV':id==='rhr'?'Resting HR':c.label}</button>)}</div><p><strong>{round(average,metric==='hrv'?1:0)}</strong> {config.unit} <span>· {values.length}-reading average</span></p></div><div className="recovery-chart">{values.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={history} margin={{left:0,right:15,top:20,bottom:0}}><defs><linearGradient id="recovery-trend" x1="0" y1="0" x2="0" y2="1"><stop stopColor={config.color} stopOpacity={.25}/><stop offset="1" stopColor={config.color} stopOpacity={0}/></linearGradient></defs><XAxis dataKey="date" axisLine={false} tickLine={false} minTickGap={35} tick={{fill:'#8b8196',fontSize:11}}/><YAxis domain={metric==='recovery'?[0,100]:['auto','auto']} axisLine={false} tickLine={false} width={35} tick={{fill:'#8b8196',fontSize:11}}/><Tooltip contentStyle={{borderRadius:14,border:'1px solid #e9e3ed',fontSize:13}} formatter={v=>[`${round(v,1)} ${config.unit}`,config.label]}/><ReferenceLine y={average} stroke="#bbb1c7" strokeDasharray="4 5"/><Area type="monotone" dataKey="value" stroke={config.color} strokeWidth={2.5} fill="url(#recovery-trend)" connectNulls={false} dot={{r:3,fill:config.color,strokeWidth:0}} isAnimationActive={false}/></AreaChart></ResponsiveContainer>:<p className="empty-movement">Your recovery history will appear after a sync.</p>}</div><p className="form-note">Showing {history.length} available readings. The dashed line is the average for this view.</p></section></div>;
}
