import {useDialog} from './ApexInteractions';
import {useEffect,useRef,useState} from 'react';
import RecoverySculpture from './RecoverySculpture';
import './ApexUI.css';

const paths={home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z',activity:'M3 12h4l3-8 4 16 3-8h4',plan:'M5 5h14v16H5z M8 2v6m8-6v6M5 11h14',nutrition:'M8 3v7m-3-7v7c0 4 6 4 6 0V3M8 13v8M18 3v18m0-18c-5 3-5 9 0 9',recovery:'M20 14A8 8 0 0 1 10 4a8 8 0 1 0 10 10Z',gym:'M3 8v8m3-11v14m12-14v14m3-11v8M6 12h12',coach:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z',profile:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21v-2a8 8 0 0 1 16 0v2',races:'M5 21V3m0 1c5-4 9 4 15 0v10c-6 4-10-4-15 0',arrow:'M5 12h14m-6-6 6 6-6 6',plus:'M12 5v14M5 12h14'};
export function Icon({name,size=22}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.activity}/></svg>;}
const navigation=[['home','Today'],['plan','Training'],['activity','Activities'],['recovery','Recovery'],['nutrition','Nutrition'],['gym','Strength'],['coach','Coach']];
const headings={plan:['Your next chapter.','Training'],activity:['Every effort counts.','Activities'],recovery:['Come back stronger.','Recovery'],nutrition:['Fuel your ambition.','Nutrition'],gym:['Built for more.','Strength'],coach:['A little perspective.','Your coach'],profile:['Made around you.','Your profile'],races:['Something to chase.','Race calendar']};
export function Frame({page,nav,athlete,dark,setDark,preview,children}){
 const positions=useRef({}),previous=useRef(page);
 const scroll=useRef(null),[menu,setMenu]=useState(false);
 useDialog(menu,()=>setMenu(false));
 useEffect(()=>{previous.current=page;if(scroll.current)scroll.current.scrollTop=positions.current[page]||0;setMenu(false);},[page]);
 return <div className={`apex-app ${dark?'apex-dark':''}`}>
  <div className="apex-workspace" ref={scroll} onScroll={e=>{positions.current[previous.current]=e.currentTarget.scrollTop;}}>
   <header className="apex-top"><button className="wordmark" onClick={()=>nav('home')}>APEX<span>PERSONAL PERFORMANCE</span></button><div className="top-actions">{preview&&<span className="preview-label">Design preview · sample data</span>}<button className="theme-button" onClick={()=>setDark(!dark)} aria-label={dark?'Use light appearance':'Use dark appearance'}>{dark?'◐':'◑'}</button><button className="athlete-button" onClick={()=>nav('profile')}><span>{athlete?.firstname?.[0]||'A'}</span>{athlete?.firstname||'Your profile'}</button></div></header>
   <main className={`apex-content screen-${page}`} id="main-content">{page!=='home'&&<div className="section-heading"><span className="eyebrow">{headings[page]?.[1]}</span><h1>{headings[page]?.[1]}</h1></div>}{children}</main>
   <footer className="apex-footer"><span>APEX</span><span>Progress is personal.</span></footer>
  </div>
  <nav className="apex-dock" aria-label="Main navigation">{navigation.map(([id,label])=><button key={id} aria-label={label} aria-current={page===id?'page':undefined} className={page===id?'selected':''} onClick={()=>nav(id)}><span className="dock-icon"><Icon name={id}/></span><span>{label}</span></button>)}</nav>
  <nav className="apex-mobile-nav" aria-label="Mobile navigation">{[['home','Today'],['plan','Training'],['nutrition','Fuel'],['coach','Coach']].map(([id,label])=><button key={id} aria-label={label} aria-current={page===id?'page':undefined} className={page===id?'selected':''} onClick={()=>nav(id)}><span className="dock-icon"><Icon name={id}/></span><span>{label}</span></button>)}<button aria-label="Explore" aria-expanded={menu} aria-haspopup="dialog" className={!['home','plan','nutrition','coach'].includes(page)?'selected':''} onClick={()=>setMenu(!menu)}><span className="dock-icon"><Icon name="plus"/></span><span>Explore</span></button></nav>
  {menu&&<div className="explore-backdrop" onClick={e=>{if(e.target===e.currentTarget)setMenu(false);}}><section className="explore-sheet" role="dialog" aria-modal="true" aria-labelledby="explore-title"><div className="sheet-handle"/><div className="stage-top"><span className="eyebrow">YOUR PERSONAL PERFORMANCE SPACE</span><button className="close-button" onClick={()=>setMenu(false)} aria-label="Close explore menu">×</button></div><h2 id="explore-title">More of the picture.</h2><div className="explore-grid">{[['recovery','Recovery','Listen to your body.'],['activity','Activities','A record of showing up.'],['gym','Strength','Built one rep at a time.'],['profile','You & your goals','Make it personal.']].map(([id,label,description])=><button key={id} className={'explore-tile explore-'+id} onClick={()=>{nav(id);setMenu(false);}}><Icon name={id} size={28}/><h3>{label}</h3><p>{description}</p><Icon name="arrow" size={18}/></button>)}</div><button className="explore-races" onClick={()=>{nav('races');setMenu(false);}}><Icon name="races" size={23}/><div><strong>Your race calendar</strong><span>Keep the finish line in sight.</span></div><Icon name="arrow" size={20}/></button><p className="explore-signoff">Progress is personal.</p></section></div>}

 </div>;
}
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const number=(n,d=0)=>Number.isFinite(Number(n))?Number(n).toLocaleString('en-GB',{maximumFractionDigits:d}):'—';
export function RecoveryHero({whoop,whoopOk,connectWhoop,nav}){
 const record=whoop?.recoveries?.records?.[0],raw=record?.score?.recovery_score,score=raw==null?null:Math.round(raw);
 const sleep=whoop?.sleeps?.records?.[0]?.score;
 const date=record?.created_at||record?.updated_at;
 return <section className="recovery-stage"><div className="stage-top"><span className="eyebrow">YOUR RECOVERY</span><span className="source-label"><i/>{whoopOk?'WHOOP':'NOT CONNECTED'}</span></div>
 <div className="sculpture-wrap"><RecoverySculpture score={score}/><div className="sculpture-score"><strong>{score??'—'}{score!==null&&<sup>%</sup>}</strong><span>{score===null?'Awaiting data':score>=67?'Well recovered':score>=34?'Moderate':'Low recovery'}</span></div></div>
 <div className="recovery-caption"><h2>{score===null?'Meet your baseline.':score>=67?'Room to push forward.':score>=34?'Find your balance.':'Make space to recover.'}</h2><p>{score===null?'Bring your sleep and recovery into view.':'Your latest recovery, with the signals behind it.'}</p></div>
 <div className="recovery-signals"><div><span>HRV</span><strong>{record?.score?.hrv_rmssd_milli==null?'—':number(record.score.hrv_rmssd_milli)}<small> ms</small></strong></div><div><span>Resting heart rate</span><strong>{record?.score?.resting_heart_rate??'—'}<small> bpm</small></strong></div><div><span>Sleep performance</span><strong>{sleep?.sleep_performance_percentage??'—'}<small>%</small></strong></div></div>
 <button className="stage-link" onClick={whoopOk?()=>nav('recovery'):connectWhoop}>{whoopOk?'Explore recovery':'Connect WHOOP'}<span>{date?new Date(date).toLocaleDateString('en-GB',{day:'numeric',month:'short'}):''}</span><Icon name="arrow" size={19}/></button></section>;
}
export function Home({acts=[],whoop,whoopOk,connectWhoop,athlete,plan,nav,userPrefs,prefsUnavailable=false,planUnavailable=false}){
 const now=new Date(),today=dateKey(now),monday=new Date(now);monday.setHours(0,0,0,0);monday.setDate(now.getDate()-(now.getDay()+6)%7);
 const days=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(d.getDate()+i);return {key:dateKey(d),label:d.toLocaleDateString('en-GB',{weekday:'short'}),km:acts.filter(a=>(a.type==='Run'||a.sport_type==='Run')&&(a.start_date_local||a.start_date||'').slice(0,10)===dateKey(d)).reduce((s,a)=>s+(a.distance||0)/1000,0)};});
 const km=days.reduce((s,d)=>s+d.km,0),max=Math.max(...days.map(d=>d.km),1);
 const sessions=plan?.sessions||[];
 const session=sessions.find(s=>!s.done&&(s.date?s.date===today:s.day?.toLowerCase().slice(0,3)===now.toLocaleDateString('en-GB',{weekday:'short'}).toLowerCase()))||sessions.find(s=>!s.done&&s.date&&s.date>=today);
 const food=userPrefs?.nutrition?.[today]||{},targets={kcal:3000,protein:140,carbs:300,...userPrefs?.nutritionTargets};
 const recent=acts.slice(0,3);
 return <div className="today-layout"><div className="today-heading"><div><span className="eyebrow">{now.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'})}</span><h1>Your everyday.<br/><em>Elevated.</em></h1></div><p>{athlete?.firstname?`${athlete.firstname}, your`:'Your'} training, recovery and fuel. <br/>One clearer picture.</p></div>
 <div className="hero-grid"><RecoveryHero {...{whoop,whoopOk,connectWhoop,nav}}/><div className="hero-right">{planUnavailable?<section className="session-stage"><h2>Plan temporarily unavailable</h2><p>Your saved plan could not load. Retry saved data to restore it.</p></section>:<section className="session-stage"><div className="stage-top"><span className="eyebrow">{session?'ON YOUR PLAN':'YOUR NEXT CHAPTER'}</span><Icon name="plan"/></div><h2>{session?.type||'Make a plan.'}</h2><p>{session?session.notes||plan?.title:'Give your ambition a little structure.'}</p><div className="session-distance">{session?.dist?parseFloat(session.dist)||session.dist:'Start here'}{parseFloat(session?.dist)>0&&<span> km</span>}</div><svg className="terrain" viewBox="0 0 600 190" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="terrain-shade" x2="0" y2="1"><stop stopColor="#aaa1f7" stopOpacity=".4"/><stop offset="1" stopColor="#aaa1f7" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3,4,5,6,7].map(i=><path key={i} d={`M-20 ${165+i*7} C70 ${160+i*6},105 ${65+i*10},190 ${110+i*6} S310 ${150+i*4},365 ${60+i*7} S480 ${30+i*9},620 ${90+i*7}`} fill="none" stroke="#aea3fa" strokeOpacity={.35-i*.025} strokeWidth="1"/>)}<path d="M-20 165 C70 160,105 65,190 110 S310 150,365 60 S480 30,620 90 L620 220H-20Z" fill="url(#terrain-shade)"/></svg><div className="session-bottom"><span>{session?.pace?`${session.pace} /km`:session?.date||'Built around your goals'}</span><button onClick={()=>nav(session?'plan':'coach')} aria-label={session?'View training plan':'Build a training plan'}><Icon name="arrow"/></button></div></section>}
 <section className="weekly-stage"><div className="stage-top"><span className="eyebrow">THIS WEEK’S RUNNING</span><button className="text-button" onClick={()=>nav('activity')}>View activity <Icon name="arrow" size={16}/></button></div><div className="weekly-data"><strong>{number(km,1)}<small> km</small></strong><span>{days.filter(d=>d.km>0).length} active days</span></div><div className="week-bars" aria-label="Running distance this week">{days.map(d=><div key={d.key} className={d.key===today?'is-today':''}><div className="bar-track"><div style={{height:`${Math.max(d.km/max*100,d.km?5:0)}%`}} title={`${d.label}: ${number(d.km,1)} km`}/></div><span>{d.label[0]}</span></div>)}</div></section></div></div>
 {!prefsUnavailable&&<section className="fuel-strip"><div className="fuel-intro"><span className="eyebrow">DAILY NUTRITION</span><h2>Fuel the work.</h2><button className="text-button" onClick={()=>nav('nutrition')}>Log a meal <Icon name="plus" size={17}/></button></div>{[['kcal','Energy','kcal'],['protein','Protein','g'],['carbs','Carbs','g']].map(([key,label,unit])=><div className={`fuel-stat fuel-${key}`} key={key}><span>{label}</span><strong>{number(Number(food[key]||0))}<small> / {targets[key]} {unit}</small></strong><div className="fuel-track"><i style={{width:`${Math.min(100,(Number(food[key])||0)/targets[key]*100)}%`}}/></div></div>)}</section>}
 <section className="recent-section"><div className="section-label"><div><span className="eyebrow">THE WORK YOU’VE PUT IN</span><h2>Recent movement.</h2></div><button className="text-button" onClick={()=>nav('activity')}>All activities <Icon name="arrow" size={18}/></button></div><div className="recent-grid">{recent.length?recent.map((a,i)=><button className="movement-card" key={a.id||i} onClick={()=>nav('activity',a.id)}><div className="movement-meta"><Icon name={a.type==='Run'?'activity':'gym'}/><span>{new Date(a.start_date_local||a.start_date).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</span></div><h3>{a.name}</h3><div><strong>{a.distance?number(a.distance/1000,1):Math.round((a.moving_time||0)/60)}</strong><span>{a.distance?' km':' min'}</span><span className="movement-type">{a.type}</span></div></button>):<div className="empty-movement">Your synced activities will appear here.</div>}</div></section>
 </div>;
}
export function Welcome({url}){return <div className="apex-welcome"><div className="welcome-copy"><span className="wordmark">APEX</span><span className="eyebrow">PERSONAL PERFORMANCE</span><h1>All of you.<br/><em>Moving forward.</em></h1><p>A more connected view of your training, recovery and nutrition.</p><a href={url}>Connect with Strava <Icon name="arrow"/></a><span className="welcome-note">Connect your existing account to get started.</span></div><div className="welcome-art"><RecoverySculpture score={76}/><span>TRAIN · RECOVER · FUEL · REPEAT</span></div></div>}
