import {useState} from 'react';
import {localDate,datedSessions} from './ApexTraining';
import {focusRace,raceDate} from './ApexGoals';
export default function Journal({userPrefs,onSavePrefs,plan,nav}){
 const today=localDate(new Date()),journal=userPrefs?.journal||{},[date,setDate]=useState(today),[editing,setEditing]=useState(false),[draft,setDraft]=useState({}),[notice,setNotice]=useState('');
 const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return localDate(d);}),entries=days.filter(d=>journal[d]),sessions=datedSessions(plan).filter(s=>days.includes(s.date)),foods=days.filter(d=>userPrefs?.nutrition?.[d]),goal=focusRace(userPrefs?.races);
 return <section className="daily-review"><div className="section-label"><div><span className="eyebrow">THE HUMAN SIDE OF YOUR DATA</span><h2>Your daily check-in</h2></div><button className="secondary-action" onClick={()=>{setDraft(journal[date]||{energy:3,soreness:1,stress:3,notes:''});setEditing(!editing);}}>{editing?'Close':journal[date]?'Edit check-in':'Check in'}</button></div><div className="checkin-days">{days.map(d=><button key={d} aria-pressed={date===d} onClick={()=>{setDate(d);setEditing(false);}}><span>{new Date(d+'T12:00:00').toLocaleDateString('en-GB',{weekday:'short'})}</span><strong>{new Date(d+'T12:00:00').getDate()}</strong><i>{journal[d]?'•':'·'}</i></button>)}</div>
 {editing?<form className="checkin-form" onSubmit={e=>{e.preventDefault();onSavePrefs({...userPrefs,journal:{...journal,[date]:{...draft,updatedAt:new Date().toISOString()}}});setEditing(false);setNotice('Check-in added.');}}>{[['energy','Energy','Low','High'],['soreness','Soreness','None','High'],['stress','Stress','Low','High']].map(([k,l,low,high])=><label key={k}>{l}<div className="checkin-scale">{[1,2,3,4,5].map(n=><button type="button" key={n} aria-label={`${l} ${n} of 5`} aria-pressed={draft[k]===n} onClick={()=>setDraft({...draft,[k]:n})}>{n}</button>)}</div><small>{low} → {high}</small></label>)}<label>A note to yourself<textarea rows={2} value={draft.notes||''} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><button className="primary-action">Save check-in</button></form>:<p className="checkin-summary">{journal[date]?`Energy ${journal[date].energy}/5 · Soreness ${journal[date].soreness}/5 · Stress ${journal[date].stress}/5${journal[date].notes?' — '+journal[date].notes:''}`:'How did it feel? Your own experience adds something a wearable cannot.'}</p>}
 {notice&&<p role="status" className="form-note">{notice}</p>}<details className="week-review"><summary>Your last 7 days <span>Review →</span></summary><div className="review-metrics"><div><strong>{sessions.filter(s=>s.done).length}/{sessions.length}</strong><span>plan sessions complete</span></div><div><strong>{foods.length}/7</strong><span>days with food logged</span></div><div><strong>{entries.length}/7</strong><span>check-ins</span></div></div><p>Counts reflect your APEX entries, including partial food logs. Check-ins describe how you felt; they don’t establish what caused changes in recovery.</p><button className="text-button" onClick={()=>nav('plan')}>Review your plan →</button></details>{goal&&<button className="goal-link" onClick={()=>nav('races')}><div><span className="eyebrow">{goal.next?'YOUR PRIMARY GOAL':'ON YOUR HORIZON'}</span><strong>{goal.name}</strong><span>{goal.target||'Your next finish line'}{raceDate(goal)?' · '+goal.date:''}</span></div><span>Edit goal →</span></button>}</section>;
}
export function PersonalSettings({userPrefs,onSavePrefs}){const [p,setP]=useState(userPrefs?.profile||{}),[saved,setSaved]=useState(false);return <section className="personal-settings"><div className="section-label"><h2>Your coaching profile</h2><button className="text-button" onClick={()=>{const blob=new Blob([JSON.stringify({format:'apex-personal-export-v1',exportedAt:new Date().toISOString(),preferences:userPrefs},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='apex-personal-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Export my APEX data</button></div><p className="form-note">These are the details your coach uses. Change them whenever your circumstances change.</p><form className="meal-fields" onSubmit={e=>{e.preventDefault();onSavePrefs({...userPrefs,profile:p});setSaved(true);}}>{[['name','Preferred name'],['focus','What are you working towards?'],['availability','Training availability'],['experience','Running and lifting experience'],['constraints','Injuries, constraints or preferences']].map(([k,l])=><label key={k}>{l}<input value={p[k]||''} onChange={e=>{setP({...p,[k]:e.target.value});setSaved(false);}}/></label>)}<button className="primary-action">Save profile</button>{saved&&<p role="status">Profile updated.</p>}</form></section>;}
